## Create samplesheet and fasta

In [99]:
import pandas as pd
from pathlib import Path

In [100]:
missing_df = pd.read_csv("mane_missing.csv")
missing_df

         refseq_prot uniprot_accession(s) uniprot_isoform(s)
0        NP_001597.2               Q9BZC7           Q9BZC7-3
1        NP_942131.1               Q13085           Q13085-4
2        NP_899233.1               Q16515           Q16515-2
3        NP_004026.2               Q15067           Q15067-2
4     NP_001123476.1               P12814           P12814-3
...              ...                  ...                ...
1630  NP_001369375.2           A0A8I5KQN6                NaN
1631  NP_001091883.3               A6NGK3                NaN
1632  NP_001383000.1                  NaN                NaN
1633  NP_001306939.1                  NaN                NaN
1634  NP_001334613.1               Q9BT76           Q9BT76-3

[1635 rows x 3 columns]

In [101]:
seq_df = pd.read_csv("seq_for_mut_prob.tsv", sep="\t")
seq_df

,Gene,Ens_Gene_ID,Ens_Transcr_ID,Uniprot_ID,F,Seq,Chr,Reverse_strand,Exons_coord,Seq_dna,Tri_context,Reference_info
0,ZZZ3,ENSG00000036549,ENST00000370801,Q8IYH5,1,MAASRSTRVTRSTVGLNGLDESFCGRTLRNRSIAHPEEISSNSQVR...,NC_000001.11,1.0,NaN,ATGGCTGCTTCCCGATCTACTCGTGTTACAAGATCAACAGTGGGGT...,"CAT,ATG,TGG,GGC,GCT,CTG,TGC,GCT,CTT,TTC,TCC,CC...",0
1,ZZEF1,ENSG00000074755,ENST00000381638,O43149,9M,MGNAPSHSSEDEAAAAGGEGWGPHQDWAAVSGTTPGPGVAAPALPP...,17,1.0,"[(4142895, 4142542), (4124051, 4123907), (4117...",ATGGGGAACGCTCCGAGTCACAGCAGTGAAGACGAAGCGGCAGCTG...,"CAT,ATG,TGG,GGG,GGG,GGA,GAA,AAC,ACG,CGC,GCT,CT...",1
2,ZYX,ENSG00000159840,ENST00000322764,Q15942,1,MAAPRPSPAISVSVSAPAFYAPQKKFGPVVAPKPKVNPFRPGDSEP...,NC_000007.14,0.0,NaN,ATGGCGGCCCCCCGCCCGTCTCCCGCGATCTCCGTTTCGGTCTCGG...,"CAT,ATG,TGG,GGC,GCG,CGG,GGC,GCC,CCC,CCC,CCC,CC...",0
3,ZYG11B,ENSG00000162378,ENST00000294353,Q9C0D3,1,MPEDQAGAAMEEASPYSLLDICLNFLTTHLEKFCSARQDGTLCLQE...,NC_000001.11,0.0,NaN,ATGCCCGAGGACCAGGCCGGCGCAGCCATGGAGGAGGCGTCTCCCT...,"CAT,ATG,TGC,GCC,CCC,CCG,CGA,GAG,AGG,GGA,GAC,AC...",0
4,ZYG11A,ENSG00000203995,ENST00000371528,Q6WRX3,1,MVHFLHPGHTPRNIVPPDAQKDALGCCVVQEEASPYTLVNICLNVL...,NC_000001.11,0.0,NaN,ATGGTTCATTTCTTGCACCCGGGCCACACGCCCCGGAACATCGTCC...,"CAT,ATG,TGG,GGT,GTT,TTC,TCA,CAT,ATT,TTT,TTC,TC...",0
...,...,...,...,...,...,...,...,...,...,...,...,...
19167,A3GALT2,ENSG00000184389,ENST00000442999,U3KPV4,1,MALKEGLRAWKRIFWRQILLTLGLLGLFLYGLPKFRHLEALIPMGV...,NC_000001.11,1.0,NaN,ATGGCTCTCAAGGAGGGACTCAGGGCCTGGAAGAGAATCTTCTGGC...,"CAT,ATG,TGG,GGC,GCT,CTC,TCT,CTC,TCA,CAA,AAG,AG...",0
19168,A2ML1,ENSG00000166535,ENST00000299698,A8K2U0,1,MWAQLLLGMLALSPAIAEELPNYLVTLPARLNFPSVQKVCLDLSPG...,NC_000012.12,0.0,NaN,ATGTGGGCTCAGCTCCTTCTAGGAATGTTGGCCCTATCACCAGCCA...,"CAT,ATG,TGT,GTG,TGG,GGG,GGC,GCT,CTC,TCA,CAG,AG...",0
19169,A2M,ENSG00000175899,ENST00000318602,P01023,1,MGKNKLLHPSLVLLLLVLLPTDASVSGKPQYMVLVPSLLHTETTEK...,NC_000012.12,1.0,NaN,ATGGGGAAGAACAAACTCCTTCATCCAAGTCTGGTTCTTCTCCTCT...,"CAT,ATG,TGG,GGG,GGG,GGA,GAA,AAG,AGA,GAA,AAC,AC...",0
19170,A1CF,ENSG00000148584,ENST00000373997,A0A024QZJ5,1,MESNHKSGDGLSGTQKEAALRALVQRTGYSLVQENGQRKYGGPPPG...,NC_000010.11,1.0,NaN,ATGGAATCAAATCACAAATCCGGGGATGGATTGAGCGGCACTCAGA...,"CAT,ATG,TGG,GGA,GAA,AAT,ATC,TCA,CAA,AAA,AAT,AT...",0
19171,A1BG,ENSG00000121410,ENST00000263100,P04217,1,MSMLVVFLLLWGVTWGPVTEAAIFYETQPSLWAESESLLKPLANVT...,NC_000019.10,1.0,NaN,ATGTCCATGCTCGTGGTCTTTCTCTTGCTGTGGGGTGTCACCTGGG...,"CAT,ATG,TGT,GTC,TCC,CCA,CAT,ATG,TGC,GCT,CTC,TC...",0

In [102]:
def write_fasta(row, outpath="./fasta_toy"):
    outpath = Path(outpath)
    outpath.mkdir(parents=True, exist_ok=True)
    fasta = f">{row.Uniprot_ID} {row.Gene}, , {len(row.Seq)} residues\n{row.Seq}\n"
    fullpath = outpath / f"{row.Uniprot_ID}.fasta"
    fullpath.write_text(fasta)
    
    return fullpath

genes = ["TP53", "CTNNB1", "BRAF", "NRAS", "ERBB2", "PTEN", "EGFR", "SMAD4", "FBXW7", "NFE2L2"]
subset = seq_df[seq_df.Gene.isin(genes)].reset_index(drop=True)[["Gene", "Uniprot_ID", "Ens_Transcr_ID", "Seq"]]
samplesheet = []

for _, row in subset.iterrows():
    fullpath = write_fasta(row)
    samplesheet.append({
        "sequence": row.Uniprot_ID,
        "fasta": str(fullpath)
        })

samplesheet = pd.DataFrame(samplesheet)
samplesheet.to_csv("samplesheet_toy.csv", index=False)
samplesheet

     sequence                       fasta
0      K7PPA8      fasta_toy/K7PPA8.fasta
1  A0A024R274  fasta_toy/A0A024R274.fasta
2      F6KD01      fasta_toy/F6KD01.fasta
3      P01111      fasta_toy/P01111.fasta
4      Q16236      fasta_toy/Q16236.fasta
5      Q969H0      fasta_toy/Q969H0.fasta
6      P04626      fasta_toy/P04626.fasta
7      P00533      fasta_toy/P00533.fasta
8  A0A024R2Q3  fasta_toy/A0A024R2Q3.fasta
9      P15056      fasta_toy/P15056.fasta

## Check similarity between two structures

In [87]:
# FILES=("AF-K7PPA8-F1-model_v4.pdb" "AF-A0A024R274-F1-model_v4.pdb" "AF-F6KD01-F1-model_v4.pdb" "AF-P01111-F1-model_v4.pdb" "AF-Q16236-F1-model_v4.pdb" "AF-Q969H0-F1-model_v4.pdb" "AF-P04626-F1-model_v4.pdb" "AF-P00533-F1-model_v4.pdb" "AF-A0A024R2Q3-F1-model_v4.pdb" "AF-P15056-F1-model_v4.pdb")
# for file in "${FILES[@]}"; do     scp -P 22022 spellegrini@bbgcluster:/workspace/nobackup/scratch/oncodrive3d/datasets_mane_240506/pdb_structures/$file ./pdb/; done

In [58]:
from Bio import PDB

def compute_rmsd_ca_safely(pdb1_path, pdb2_path):
    """
    Compute RMSD on matching C-alpha atoms and also return
    the percentage of matching residues.
    
    RMSD < 2 Ã… â†’ excellent prediction
    RMSD 2â€“4 Ã… â†’ still very good
    RMSD > 4 Ã… â†’ likely serious differences (different conformations or errors)
    """

    parser = PDB.PDBParser(QUIET=True)

    structure1 = parser.get_structure('structure1', pdb1_path)
    structure2 = parser.get_structure('structure2', pdb2_path)

    model1 = structure1[0]
    model2 = structure2[0]

    atoms1 = []
    atoms2 = []

    chain1 = model1.child_dict.get("A")
    chain2 = model2.child_dict.get("A")

    if chain1 is None or chain2 is None:
        return None, 0.0

    # Map residues by residue number
    residues1 = {res.id[1]: res for res in chain1 if "CA" in res}
    residues2 = {res.id[1]: res for res in chain2 if "CA" in res}

    # Find common residue numbers
    common_residues = sorted(set(residues1.keys()) & set(residues2.keys()))

    if len(common_residues) == 0:
        return None, 0.0

    # Select matching CA atoms
    for res_id in common_residues:
        atoms1.append(residues1[res_id]["CA"])
        atoms2.append(residues2[res_id]["CA"])

    # Superimpose and calculate RMSD
    super_imposer = PDB.Superimposer()
    super_imposer.set_atoms(atoms1, atoms2)
    rmsd = super_imposer.rms

    # Calculate match percentage
    total_residues = max(len(residues1), len(residues2))
    match_percentage = (len(common_residues) / total_residues) * 100

    return rmsd, match_percentage

p1, p2 = "pdb_toy/AF-P04626-F1-model_v4.pdb","pdb_toy/AF-F6KD01-F1-model_v4.pdb"
rmsd_value, match_pct = compute_rmsd_ca_safely(p1, p2)
print(f"RMSD: {rmsd_value:.3f} Ã…")
print(f"Matching residues: {match_pct:.1f}%")

rmsd_value, match_pct = compute_rmsd_ca_safely(p1, p1)
print(f"RMSD: {rmsd_value:.3f} Ã…")
print(f"Matching residues: {match_pct:.1f}%")

RMSD: 29.366 Ã…
Matching residues: 32.1%
RMSD: 0.000 Ã…
Matching residues: 100.0%

## Get sequence from Uniprot ID

In [ ]:
import pandas as pd
import requests
from tqdm import tqdm
import numpy as np

def get_uniprot_sequence(accession):
    """Fetch sequence from UniProt API given an accession."""
    if pd.isna(accession):
        return np.nan
    
    url = f"https://rest.uniprot.org/uniprotkb/{accession}.fasta"
    response = requests.get(url)

    if response.status_code == 200:
        fasta_text = response.text
        lines = fasta_text.splitlines()
        sequence = ''.join(lines[1:]) 
        return sequence
    else:
        return np.nan


def fetch_sequences(df):
    """Fetch sequences following isoform > accession > NA logic."""
    sequences = []
    lengths = []
    
    for _, row in tqdm(df.iterrows(), total=len(df), desc="Fetching sequences"):
        if not pd.isna(row['uniprot_isoform(s)']):
            seq = get_uniprot_sequence(row['uniprot_isoform(s)'])
        elif not pd.isna(row['uniprot_accession(s)']):
            seq = get_uniprot_sequence(row['uniprot_accession(s)'])
        else:
            seq = np.nan
        sequences.append(seq)
        lengths.append(len(seq) if not pd.isna(seq) else np.nan)
    
    df['sequence'] = sequences
    df['lengths'] = lengths
    
    return df

In [69]:
df_with_sequences = fetch_sequences(missing_df)
df_with_sequences

,refseq_prot,uniprot_accession(s),uniprot_isoform(s),sequence,lengths
0,NP_001597.2,Q9BZC7,Q9BZC7-3,MGFLHQLQLLLWKNVTLKRRSPWVLAFEIFIPLVLFFILLGLRQKK...,2436.0
1,NP_942131.1,Q13085,Q13085-4,MWWSTLMSILRARSFWKWISTQTVRIIRAVRAHFGGIMDEPSPLAQ...,2383.0
2,NP_899233.1,Q16515,Q16515-2,MSRIGGAGLPAAALTGPGRFRMAREEPAPAALAAAGQPGGGRGGER...,563.0
3,NP_004026.2,Q15067,Q15067-2,MNPDLRRERDSASFNPELLTHILDGSPEKTRRRREIENMILNDPDF...,660.0
4,NP_001123476.1,P12814,P12814-3,MDHYDSQQTNDYMQPEEDWDRDLLLDPAWEKQQRKTFTAWCNSHLR...,914.0
...,...,...,...,...,...
1630,NP_001369375.2,A0A8I5KQN6,NaN,MWPQPHLPTHPHLPTHPHLPTHPMMSKETRQSKLAEAKEQLTDHHP...,649.0
1631,NP_001091883.3,A6NGK3,NaN,MSWRGRSTYRPRPRRYVEPPEMIGPMLPEQFSDEVEPATPEEGEPA...,116.0
1632,NP_001383000.1,NaN,NaN,NaN,NaN
1633,NP_001306939.1,NaN,NaN,NaN,NaN
1634,NP_001334613.1,Q9BT76,Q9BT76-3,MGLPWGQPHLGLQMLLLALNCLRPSLSLELVPYTPQITAWDLEGKV...,276.0

In [72]:
df_with_sequences_short = df_with_sequences[df_with_sequences["lengths"] < 2400].reset_index(drop=True)
df_with_sequences_short

,refseq_prot,uniprot_accession(s),uniprot_isoform(s),sequence,lengths
0,NP_942131.1,Q13085,Q13085-4,MWWSTLMSILRARSFWKWISTQTVRIIRAVRAHFGGIMDEPSPLAQ...,2383.0
1,NP_899233.1,Q16515,Q16515-2,MSRIGGAGLPAAALTGPGRFRMAREEPAPAALAAAGQPGGGRGGER...,563.0
2,NP_004026.2,Q15067,Q15067-2,MNPDLRRERDSASFNPELLTHILDGSPEKTRRRREIENMILNDPDF...,660.0
3,NP_001123476.1,P12814,P12814-3,MDHYDSQQTNDYMQPEEDWDRDLLLDPAWEKQQRKTFTAWCNSHLR...,914.0
4,NP_001103.1,P78563,P78563-2,MDIEDEENMSSSSTDVKENRNLDNVSPKDGSTPGPGEGSQLSNGGG...,701.0
...,...,...,...,...,...
1180,NP_001350937.1,P0DPK3,P0DPK3-2,MCRDGYEPCVNEGMCVTYHNGTGYCKCPEGFLGEYCQHRDPCEKNR...,249.0
1181,NP_001342502.1,A0A8I5KY20,NaN,MDTVSLEHQIQSVQRHISFLKKEQMALLRDLHLEILRLQKRCSELT...,255.0
1182,NP_001369375.2,A0A8I5KQN6,NaN,MWPQPHLPTHPHLPTHPHLPTHPMMSKETRQSKLAEAKEQLTDHHP...,649.0
1183,NP_001091883.3,A6NGK3,NaN,MSWRGRSTYRPRPRRYVEPPEMIGPMLPEQFSDEVEPATPEEGEPA...,116.0
1184,NP_001334613.1,Q9BT76,Q9BT76-3,MGLPWGQPHLGLQMLLLALNCLRPSLSLELVPYTPQITAWDLEGKV...,276.0

In [75]:
df_with_sequences_short

,refseq_prot,uniprot_accession(s),uniprot_isoform(s),sequence,lengths
0,NP_942131.1,Q13085,Q13085-4,MWWSTLMSILRARSFWKWISTQTVRIIRAVRAHFGGIMDEPSPLAQ...,2383.0
1,NP_899233.1,Q16515,Q16515-2,MSRIGGAGLPAAALTGPGRFRMAREEPAPAALAAAGQPGGGRGGER...,563.0
2,NP_004026.2,Q15067,Q15067-2,MNPDLRRERDSASFNPELLTHILDGSPEKTRRRREIENMILNDPDF...,660.0
3,NP_001123476.1,P12814,P12814-3,MDHYDSQQTNDYMQPEEDWDRDLLLDPAWEKQQRKTFTAWCNSHLR...,914.0
4,NP_001103.1,P78563,P78563-2,MDIEDEENMSSSSTDVKENRNLDNVSPKDGSTPGPGEGSQLSNGGG...,701.0
...,...,...,...,...,...
1180,NP_001350937.1,P0DPK3,P0DPK3-2,MCRDGYEPCVNEGMCVTYHNGTGYCKCPEGFLGEYCQHRDPCEKNR...,249.0
1181,NP_001342502.1,A0A8I5KY20,NaN,MDTVSLEHQIQSVQRHISFLKKEQMALLRDLHLEILRLQKRCSELT...,255.0
1182,NP_001369375.2,A0A8I5KQN6,NaN,MWPQPHLPTHPHLPTHPHLPTHPMMSKETRQSKLAEAKEQLTDHHP...,649.0
1183,NP_001091883.3,A6NGK3,NaN,MSWRGRSTYRPRPRRYVEPPEMIGPMLPEQFSDEVEPATPEEGEPA...,116.0
1184,NP_001334613.1,Q9BT76,Q9BT76-3,MGLPWGQPHLGLQMLLLALNCLRPSLSLELVPYTPQITAWDLEGKV...,276.0

In [98]:
from pathlib import Path
import pandas as pd

def write_fasta(row, outpath="./fasta"):
    """Write a single FASTA file for a given protein entry."""
    outpath = Path(outpath)
    outpath.mkdir(parents=True, exist_ok=True)
    uni_id = row["uniprot_accession(s)"]
    fasta = f">{uni_id} {row.refseq_prot}, , {row.lengths} residues\n{row.sequence}\n"
    fullpath = outpath / f"{uni_id}.fasta"
    fullpath.write_text(fasta)
    return fullpath

def create_samplesheet(df, outpath="./fasta"):
    """Create FASTA files and a samplesheet from a subset of genes."""
    
    samplesheet_records = []

    for _, row in df.iterrows():
        fullpath = write_fasta(row, outpath=outpath)
        samplesheet_records.append({
            "sequence": row["uniprot_accession(s)"],
            "fasta": str(fullpath)
        })

    samplesheet_df = pd.DataFrame(samplesheet_records)
    return samplesheet_df


samplesheet_df = create_samplesheet(df_with_sequences_short, outpath="./fasta")
samplesheet_df.to_csv("samplesheet.csv", index=False)
samplesheet_df

        sequence                   fasta
0         Q13085      fasta/Q13085.fasta
1         Q16515      fasta/Q16515.fasta
2         Q15067      fasta/Q15067.fasta
3         P12814      fasta/P12814.fasta
4         P78563      fasta/P78563.fasta
...          ...                     ...
1180      P0DPK3      fasta/P0DPK3.fasta
1181  A0A8I5KY20  fasta/A0A8I5KY20.fasta
1182  A0A8I5KQN6  fasta/A0A8I5KQN6.fasta
1183      A6NGK3      fasta/A6NGK3.fasta
1184      Q9BT76      fasta/Q9BT76.fasta

[1185 rows x 2 columns]

In [95]:
samplesheet_df

        sequence                   fasta
0         Q13085      fasta/Q13085.fasta
1         Q16515      fasta/Q16515.fasta
2         Q15067      fasta/Q15067.fasta
3         P12814      fasta/P12814.fasta
4         P78563      fasta/P78563.fasta
...          ...                     ...
1180      P0DPK3      fasta/P0DPK3.fasta
1181  A0A8I5KY20  fasta/A0A8I5KY20.fasta
1182  A0A8I5KQN6  fasta/A0A8I5KQN6.fasta
1183      A6NGK3      fasta/A6NGK3.fasta
1184      Q9BT76      fasta/Q9BT76.fasta

[1185 rows x 2 columns]

## Upload to cluster

In [94]:
# scp -P 22022 fasta_toy/* spellegrini@bbgcluster:<cluster_path>
# scp -P 22022 samplesheet_toy.csv spellegrini@bbgcluster:<cluster_path>

## Issue of missing entries